// uniq.team — v3. CRO doctrine:
//  · One idea per section, minimal words, the product visibly RUNNING (AppDemo).
//  · Platform-first: primary CTA = /start signup (5 free), self-host one line.
//  · Proof: carousel of REAL kits — "What if Clay pitched Ramp?" — all live pages.
//  · Postiz: self-host off the sell; Oxygen: self-playing demos, two-easing motion.

import AppDemo from "@/components/AppDemo";
import RevealFx from "@/components/RevealFx";
import ExampleCarousel, { type ExampleKit } from "@/components/ExampleCarousel";

const GITHUB = "https://github.com/getuniq/uniq";

// Real kits, generated by Uniq on this very platform (see /p/<id>).
const EXAMPLES: ExampleKit[] = [
  { seller: "Clay", prospect: "Ramp", sellerColor: "#191919", prospectColor: "#E4C355", subject: "ramp vs bill.com pages = a targeting list", url: "/p/mhc47wym0" },
  { seller: "Apollo", prospect: "Rippling", sellerColor: "#5C6CFF", prospectColor: "#4A2D1F", subject: "the demo CTA on every rippling module page", url: "/p/gectfnbxo" },
  { seller: "Oxygen", prospect: "Vercel", sellerColor: "#0A0E0B", prospectColor: "#171717", subject: "gtm infra to match vercel's agent stack pace", url: "/p/152pz5u54" },
  { seller: "Instantly", prospect: "Gong", sellerColor: "#2F6BFF", prospectColor: "#8039DF", subject: "gong's outbound volume vs inbox placement", url: "/p/9o110nu40" },
  { seller: "n8n", prospect: "Twilio", sellerColor: "#EA4B71", prospectColor: "#F22F46", subject: "the workflow layer behind Orchestrator's launch", url: "/p/kk14urriv" },
  { seller: "HubSpot", prospect: "Loom", sellerColor: "#FF7A59", prospectColor: "#625DF5", subject: "the gap between Loom's slider and your CRM", url: "/p/oiz04un2i" },
];

const STACK_TOOLS: Array<{ name: string; href?: string }> = [
  { name: "Clay", href: "/for/clay" },
  { name: "Apollo", href: "/for/apollo" },
  { name: "Oxygen", href: "/for/oxygen" },
  { name: "n8n", href: "/for/n8n" },
  { name: "Instantly", href: "/for/instantly" },
  { name: "HubSpot", href: "/for/hubspot" },
  { name: "Claude Code" },
  { name: "Cursor" },
  { name: "Smartlead" },
  { name: "Make" },
  { name: "Zapier" },
  { name: "Attio" },
];

export default function Landing() {
  return (
    <div className="lp">
      <RevealFx />
      <nav className="nav">
        <a className="logo" href="/" aria-label="Uniq">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/logo.svg" alt="uniq." height={34} />
        </a>
        <div className="links">
          <a href="#examples">Examples</a>
          <a href="/pricing">Pricing</a>
          <a href="/integrations">Integrations</a>
          <a href={GITHUB}>GitHub</a>
          <a className="cta-nav" href="/start">Start free</a>
        </div>
      </nav>

      <header className="hero">
        <span className="badge">Runs in Claude · Cursor · Clay · n8n — or right here</span>
        <h1>Every prospect gets a proposal<br />in <em>their own brand</em>.</h1>
        <p className="sub">
          Two URLs in → a personalized email, a pitch page, and a hosted proposal
          wearing the prospect&apos;s colors, type, and logo.
        </p>
        <div className="ctas">
          <a className="btn primary big" href="/start">Start free — 5 proposals</a>
          <a className="btn ghost" href={GITHUB}>Star on GitHub</a>
        </div>

        <AppDemo />

        <div className="stackwall" aria-label="Works with your GTM stack">
          <div className="marquee">
            <div className="marquee-track">
              {[...STACK_TOOLS, ...STACK_TOOLS].map((t, i) =>
                t.href
                  ? <a className="toolchip linked" key={i} href={t.href}>{t.name} →</a>
                  : <span className="toolchip" key={i}>{t.name}</span>,
              )}
            </div>
          </div>
        </div>
      </header>

      {EXAMPLES.length > 0 && (
        <section className="section reveal lp-reveal center" id="examples">
          <h2>Don&apos;t take our word for it. Open these.</h2>
          <p className="lead centered">We ran the tools above through Uniq — each pitching a customer from its own website. Real generations, untouched.</p>
          <ExampleCarousel kits={EXAMPLES} />
        </section>
      )}

      <section className="section reveal lp-reveal" id="how">
        <h2>One narrative. Three artifacts.</h2>
        <div className="grid3">
          <div className="card">
            <div className="step">01 · THE HOOK</div>
            <h3>The email</h3>
            <p>Proof-of-work cold email: a real observation about them + one stealable idea. No links — deliverability is physics.</p>
          </div>
          <div className="card">
            <div className="step">02 · THE PITCH</div>
            <h3>The one-pager</h3>
            <p>A designed pitch page in <em>their</em> extracted brand. Tell your agent <code>&quot;lead with ROI&quot;</code> — it re-edits itself.</p>
          </div>
          <div className="card">
            <div className="step">03 · THE CLOSE</div>
            <h3>The hosted proposal</h3>
            <p>Trackable, animated, theirs. First open fires <code>proposal.viewed</code> — follow up at peak intent.</p>
          </div>
        </div>
      </section>

      <section className="section reveal lp-reveal" id="platform">
        <div className="platform">
          <div>
            <h2>The platform does the heavy lifting.</h2>
            <ul className="platlist">
              <li>Hosted proposal pages — soon on your own domain</li>
              <li>Engagement analytics + webhooks back to your agent</li>
              <li>Managed MCP endpoint your whole team shares</li>
              <li>Seller profile cached once, reused on every kit</li>
            </ul>
            <div className="ctas left">
              <a className="btn primary" href="/start">Start free</a>
              <a className="btn ghost" href="/pricing">Pricing — per proposal, no credits</a>
            </div>
            <p className="selfhost">Prefer your own infra? The engine is AGPL — <a href={GITHUB}>self-host free, forever</a>.</p>
          </div>
          <div className="platvisual" aria-hidden>
            <div className="pv-stat"><b>~60s</b><span>URL → closing kit</span></div>
            <div className="pv-stat"><b>3</b><span>artifacts, one narrative</span></div>
            <div className="pv-stat"><b>100%</b><span>their brand, not yours</span></div>
            <div className="pv-stat"><b>1</b><span>webhook at peak intent</span></div>
          </div>
        </div>
      </section>

      <section className="section reveal lp-reveal center" id="final">
        <h2>Your next prospect deserves better than a template.</h2>
        <div className="ctas">
          <a className="btn primary big" href="/start">Generate your first kit — free</a>
        </div>
      </section>

      <div className="watermark" aria-hidden>uniq.</div>
      <footer className="footer">
        <span>© {new Date().getFullYear()} Uniq — proudly open source</span>
        <span>
          <a href={GITHUB}>GitHub</a> · <a href="/llms.txt">llms.txt</a> · <a href="/integrations">Integrations</a> · <a href="/pricing">Pricing</a> · <a href="/api/mcp">MCP</a>
        </span>
      </footer>
    </div>
  );
}
